---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: upbound
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  skipDependencyResolution: true
  controllerConfigRef:
    name: upbound
  package: