apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: sentara-gcp-comps
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  package: us-central1-docker.pkg.dev/bradw-nextgen-devops/crossplane-testing/sentara-gcp:v0.1.0
  packagePullPolicy: always
  skipDependencyResolution: true