apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -gcp-cloudplatform

resources:
- ../base

patches:
- patch: |-
    apiVersion: pkg.crossplane.io/v1
    kind: Provider
    metadata:
      name: upbound
    spec:
      package: provider-gcp-cloudplatform

replacements:
- source:
    group: pkg.crossplane.io
    version: v1
    kind: Provider
    fieldPath: metadata.name
  targets:
  - select:
      group: pkg.crossplane.io
      version: v1
      kind: Provider
    fieldPaths:
    - spec.controllerConfigRef.name