apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- ns.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.8.4/manifests/install.yaml
- application.yaml

patches:
- path: argocd-cm.yaml