{{- range $appset := .Values.appsets }}
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ $.Release.Name }}-{{ $appset.name }}
  namespace: argocd
  labels:
    deployment: manifest
    name: {{ $.Release.Name }}-{{ $appset.name }}
    tenant: {{ $.Release.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
  - git:
      repoURL: {{ $appset.repo }}
      revision: {{ $appset.revision | default "HEAD" }}
      files:
      - path: {{ $appset.path }}
  template:
    metadata:
      name: "{{ $.Release.Name }}-{{ $appset.name }}-{{`{{ .path.basename }}` }}"
      labels:
        deployment: manifest
        name: {{ $.Release.Name }}-{{ $appset.name }}
        app: "{{`{{ .path.basename }}` }}"
        tenant: {{ $.Release.Name }}
      annotations:
        argocd.argoproj.io/sync-wave: "10"
    spec:
      project: {{ $.Release.Name }}
      source:
        repoURL: {{ $appset.repo }}
        path: "{{ `{{.path.path }}` }}"
        targetRevision: {{ $appset.revision | default "HEAD" }}
      destination:
        server: https://kubernetes.default.svc
        namespace: {{ $.Release.Name }}
      syncPolicy:
        # automated:
        #   prune: false
        #   selfHeal: true
        syncOptions:
        - CreateNamespace=true
{{- end }}