apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Release.Name }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Tenant {{ .Release.Name }}
  sourceRepos:
  - '*'
  destinations:
  - namespace: {{ .Release.Name }}
    server: '*'
  roles:
  - name: admin
    description: Admin privileges to tenant {{ .Release.Name }}
    policies:
    - p, proj:{{ .Release.Name }}:admin, applications, *, {{ .Release.Name }}/*, allow
    groups: []