apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- setup/
- cloudplatform/
- compute/
- family/
- servicenetworking/
- sql/
- storage/
- vpcaccess/

configurations:
- kustomizeconfig/xp-provider.yaml

images:
- name: provider-family-gcp
  newName: xpkg.upbound.io/upbound/provider-family-gcp
  newTag: v0.37.0
- name: provider-gcp-cloudplatform
  newName: xpkg.upbound.io/upbound/provider-gcp-cloudplatform
  newTag: v0.37.0
- name: provider-gcp-compute
  newName: xpkg.upbound.io/upbound/provider-gcp-compute
  newTag: v0.37.0
- name: provider-gcp-servicenetworking
  newName: xpkg.upbound.io/upbound/provider-gcp-servicenetworking
  newTag: v0.37.0
- name: provider-gcp-sql
  newName: xpkg.upbound.io/upbound/provider-gcp-sql
  newTag: v0.37.0
- name: provider-gcp-storage
  newName: xpkg.upbound.io/upbound/provider-gcp-storage
  newTag: v0.37.0
- name: provider-gcp-vpcaccess
  newName: xpkg.upbound.io/upbound/provider-gcp-vpcaccess
  newTag: v0.37.0