---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform-admin
  namespace: argocd
  labels:
    deployment: manifest
    name: platform-admin
    tier: cluster
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
spec:
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
  - git:
      repoURL: git@github.com:US-CHI-EVDN-CLOUDOPS/sentara-gitops-demo.git
      revision: HEAD
      files:
      - path: platform-admin/*/config.yaml
  template:
    metadata:
      name: 'platform-admin-{{.path.basename}}'
      labels:
        deployment: manifest
        name: 'platform-admin-{{.path.basename}}'
        tier: cluster
      annotations:
        argocd.argoproj.io/sync-wave: "-10"
    spec:
      project: platform-admin
      source:
        repoURL: git@github.com:US-CHI-EVDN-CLOUDOPS/sentara-gitops-demo.git
        path: '{{.path.path}}'
        targetRevision: HEAD
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .namespace }}'
      syncPolicy:
        # automated:
        #   prune: false
        #   selfHeal: true
        syncOptions:
        - CreateNamespace=true