---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenants
  namespace: argocd
  labels:
    deployment: manifest
    name: tenants
    tier: cluster
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
spec:
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
  - git:
      repoURL: git@github.com:US-CHI-EVDN-CLOUDOPS/sentara-gitops-demo.git
      revision: HEAD
      directories:
      - path: tenants/*
  template:
    metadata:
      name: '{{.path.basename}}-tenant'
      labels:
        deployment: manifest
        name: '{{.path.basename}}-tenant'
        tier: cluster
      annotations:
        argocd.argoproj.io/sync-wave: "-10"
    spec:
      project: platform
      sources:
      - chart: '{{ .chart.name }}'
        repoURL: git@github.com:US-CHI-EVDN-CLOUDOPS/sentara-gitops-demo.git
        path: tenant-chart
        helm:
          releaseName: '{{.path.basename}}'
          valueFiles:
          - "$values/{{.path.path}}/values.yaml"
      - repoURL: git@github.com:US-CHI-EVDN-CLOUDOPS/sentara-gitops-demo.git
        targetRevision: HEAD
        ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .path.basename }}'
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
        - CreateNamespace=true