apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Tenant Project
  sourceRepos: []
  destinations: []
  roles:
  - name: admin
    description: Admin privileges to tenant
    policies:
    - p, proj:replace:admin, applications, *, replace/*, allow
    groups: []